
image: registry.gitlab.com/centos/cloud/sagano-builder/base-centos:stream9

stages:
  - build

.base:
  parallel:
    matrix:
      - TIER:
          - tier-0
          - tier-1
        OS: centos
        VERSION: [stream9]
        VARIANT: ["", "-rt"]
      - TIER:
          - tier-0
          - tier-1
        OS: fedora
        VERSION: [38]
        VARIANT: [""]

test-build:
  extends: .base
  only:
    - merge_requests
  stage: build
  script:
    - rpm-ostree install distribution-gpg-keys
    - set -euo pipefail; rpm-ostree compose image --format=ociarchive --initialize ${OS}-${TIER}${VARIANT}-${VERSION}.yaml dest.oci-archive

build-push:
  extends: .base
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    COMPOSE_INITIALIZE: ""
    FORCE: ""
  stage: build
  before_script:
    # Log into the registry
    - echo "$CI_REGISTRY_PASSWORD" | skopeo login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - set -euo pipefail; rpm-ostree compose image ${COMPOSE_INITIALIZE:+--initialize} ${FORCE:+--force-nocache} --format=registry ${OS}-${TIER}${VARIANT}-${VERSION}.yaml ${CI_REGISTRY_IMAGE}/${OS}-boot-${TIER}${VARIANT}:${VERSION}

