---
include:
  - remote: https://gitlab.com/platform-engineering-org/gitlab-ci/-/raw/main/templates/build-image.gitlab-ci.yml

build-image:
  extends: .build-image
  variables:
    EXTRA_ARGS: "--security-opt=label=disable --cap-add=all"
  rules:
    - if: $CI_PROJECT_NAMESPACE != "fedora/bootc"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
