name: builder

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/builder.yml
      - builder/**

env:
  REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - run: echo IMAGE_NAME=$(echo ${{ github.repository_owner }}/builder | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login
        run: buildah login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
      - name: Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest
          containerfiles: ./builder/Containerfile
          archs: s390x, arm64, amd64, ppc64le
          oci: true
          context: builder
      - name: Push
        run: buildah push --all ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
