name: ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build-image:
    runs-on: ubuntu-latest

    container:
      image: quay.io/centos-boot/builder:latest
      options: --privileged

    strategy:
      matrix:
        os: [fedora]
        tier: [tier-1]
        include:
        - os: fedora
          version: eln

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: |
          rpm-ostree compose image --format=ociarchive \
          --initialize ${{ matrix.os }}-${{ matrix.tier }}${{ matrix.variant }}-${{ matrix.version }}.yaml \
          dest.oci-archive
