name: ci

on:

  pull_request:
    branches:
    - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    container:
      image: registry.gitlab.com/centos/cloud/sagano-builder/centos:stream9
      options: --privileged

    strategy:
      matrix:
        os: [centos, fedora]
        tier: [tier-0, tier-1]
        include:
        - os: centos
          version: stream9
        - os: centos
          variant: ""
        - os: centos
          variant: "-rt"
        - os: fedora
          version: eln
        - os: fedora
          variant: ""
        - os: fedora
          variant: "-dev"

    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Build
        run: |
          rpm-ostree compose image --format=ociarchive \
          --initialize ${{ matrix.os }}-${{ matrix.tier }}${{ matrix.variant }}-${{ matrix.version }}.yaml \
          dest.oci-archive
