name: publish-image

on:
  push:
    branches:
    - main

  workflow_dispatch:

env:
  REGISTRY: quay.io
  QUAY_ORG: centos-boot

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    container:
      image: quay.io/centos-boot/builder:latest@sha256:65ce75a3515e2711ff770b778ae9eed9eafa895e1afe222d44ca74a337e2e6e1
      options: --privileged

    strategy:
      matrix:
        os: [fedora]
        tier: [tier-1]
        include:
        - os: fedora
          version: eln

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build and Push
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | skopeo login -u "${{ secrets.QUAY_USER }}" \
          --password-stdin ${{ env.REGISTRY }}
          rpm-ostree compose image --initialize-mode if-not-exists \
          --format=registry ${{ matrix.os }}-${{ matrix.tier }}-${{ matrix.version }}.yaml \
          ${{ env.REGISTRY }}/${{ env.QUAY_ORG }}/${{ matrix.os }}-${{ matrix.tier}}:${{ matrix.version }}
